server:
  port: 19091

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth-server/**
        - id: company-server
          uri: lb://company-server
          predicates:
            - Path=/api/company-server/**
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/api/order-server/**
        - id: hub-server
          uri: lb://hub-server
          predicates:
              - Path=/api/hub-server/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


