version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/tmp/openapi3.json
    volumes:
      - ./build/api-spec/openapi3.json:/tmp/openapi3.json


volumes:
  postgres_data:
