server:
  port: 19093
spring:
  application:
    name: hub-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
      host: localhost
      username: default
      password: systempass

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

logging:
  level:
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus, refresh
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0